version: "3"
services:

  # https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    image: phpmyadmin:5.0.4
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1

  # https://hub.docker.com/_/adminer
  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8089:8080

  # https://hub.docker.com/_/mariadb
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

