FROM node:14.8.0-slim

# system local config
RUN true \
    # debian china mirrors
    && sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    # timezone to china
    && ln -sf /usr/share/zoneinfo/PRC /etc/localtime 

RUN apt-get update \
    && apt-get install -y \
    # node-sass 等编译依赖
    make gcc g++ python \
    # 命令行工具
    zsh curl wget vim git

# RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
# RUN sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
# RUN curl -Lo install.sh https://gitee.com/mirrors/oh-my-zsh/blob/master/tools/install.sh
# RUN chmod -R 0777 install.sh
# RUN sh -c install.sh

# RUN sh -c "$(curl -fsSL https://gitee.com/mirrors/oh-my-zsh/blob/master/tools/install.sh)"

RUN true \
    && npm config set registry https://registry.npm.taobao.org \
    && npm install webpack -g \  
    && npm install -g vue-cli 

RUN mkdir /opt/work

WORKDIR /opt/work

# 给这个目录执行权限，x是执行权限
RUN chmod +x /opt/work

VOLUME /opt/work

EXPOSE 8080

CMD ["zsh"]